AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 60
    Runtime: nodejs12.x
Resources:
  GetTasksFunction:
    Type: AWS::Serverless::Function
    TracingConfig:
      Mode: Active
    Properties:
      FunctionName: GetTasks
      Description: Get all tasks
      Role: arn:aws:iam::063257378709:role/LambdaExecution
      CodeUri: s3://alpha-bucket-1234/5dbaf593eeeafbca1c51d2e28f686410
      Handler: main.lambdaHandler
      Events:
        GetTasksAPI:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    TracingConfig:
      Mode: Active
    Properties:
      FunctionName: CreateTask
      Description: Create a new task
      Role: arn:aws:iam::063257378709:role/LambdaExecution
      CodeUri: s3://alpha-bucket-1234/3e4c33441d8f488d8f41116e2e1e3884
      Handler: main.lambdaHandler
      Events:
        CreateTaskAPI:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
  DetailTaskFunction:
    Type: AWS::Serverless::Function
    TracingConfig:
      Mode: Active
    Properties:
      FunctionName: DetailTask
      Description: Detail task
      Role: arn:aws:iam::063257378709:role/LambdaExecution
      CodeUri: s3://alpha-bucket-1234/6d099cec1314e33968583da424bf9962
      Handler: main.lambdaHandler
      Layers:
      - Ref: BoomLayer
      Events:
        DetailTaskAPI:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: get
  BoomLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Boom
      Description: Layer that includes the Boom library
      ContentUri: s3://alpha-bucket-1234/114bc0ce3ddf21990d9d8ef76cf0a7cd
      CompatibleRuntimes:
      - nodejs12.x
      LicenseInfo: MIT
      RetentionPolicy: Delete
Outputs:
  GetTasksAPI:
    Description: API Gateway endpoint URL for Prod stage for GetTasks function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/
  GetTasksFunction:
    Description: GetTasks Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTasksFunction
      - Arn
  CreateTaskAPI:
    Description: API Gateway endpoint URL for Prod stage for CreateTask function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/
  CreateTaskFunction:
    Description: CreateTask Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTaskFunction
      - Arn
  DetailTaskAPI:
    Description: API Gateway endpoint URL for Prod stage for DetailTask function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/
  DetailTaskFunction:
    Description: DetailTask Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DetailTaskFunction
      - Arn
  BoomLayerARN:
    Value:
      Ref: BoomLayer
    Description: BoomLayer ARN
    Export:
      Name: boom-layer-arn
