AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60
        Runtime: nodejs12.x

Resources:
    GetTasksFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: GetTasks
            Description: Get all tasks
            Role: arn:aws:iam::063257378709:role/LambdaExecution
            CodeUri: get-tasks/
            Handler: main.lambdaHandler
            Events:
                GetTasksAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /tasks
                        Method: get
    CreateTaskFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: CreateTask
            Description: Create a new task
            Role: arn:aws:iam::063257378709:role/LambdaExecution
            CodeUri: create-task/
            Handler: main.lambdaHandler
            Events:
                CreateTaskAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /tasks
                        Method: post

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    GetTasksAPI:
        Description: 'API Gateway endpoint URL for Prod stage for GetTasks function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/'
    GetTasksFunction:
        Description: 'GetTasks Lambda Function ARN'
        Value: !GetAtt GetTasksFunction.Arn
    CreateTaskAPI:
        Description: 'API Gateway endpoint URL for Prod stage for CreateTask function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/'
    CreateTaskFunction:
        Description: 'CreateTask Lambda Function ARN'
        Value: !GetAtt CreateTaskFunction.Arn
