AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60
        Runtime: nodejs12.x

Resources:
    GetTasksFunction:
        Type: AWS::Serverless::Function
        TracingConfig:
            Mode: Active
        Properties:
            FunctionName: GetTasks
            Description: Get all tasks
            Role: arn:aws:iam::063257378709:role/LambdaExecution
            CodeUri: functions/get-tasks/
            Handler: main.lambdaHandler
            Events:
                GetTasksAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /tasks
                        Method: get
                        
    CreateTaskFunction:
        Type: AWS::Serverless::Function
        TracingConfig:
            Mode: Active
        Properties:
            FunctionName: CreateTask
            Description: Create a new task
            Role: arn:aws:iam::063257378709:role/LambdaExecution
            CodeUri: functions/create-task/
            Handler: main.lambdaHandler
            Layers: 
                - !Ref UtilsLayer
            Events:
                CreateTaskAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /tasks
                        Method: post
                        
    DetailTaskFunction:
        Type: AWS::Serverless::Function
        TracingConfig:
            Mode: Active
        Properties:
            FunctionName: DetailTask
            Description:  Detail task
            Role: arn:aws:iam::063257378709:role/LambdaExecution
            CodeUri: functions/detail-task/
            Handler: main.lambdaHandler
            Layers: 
                - !Ref UtilsLayer
            Events:
                DetailTaskAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /tasks/{id}
                        Method: get
                        
    DetailTaskFunction:
        Type: AWS::Serverless::Function
        TracingConfig:
            Mode: Active
        Properties:
            FunctionName: DeleteTask
            Description:  Delete task
            Role: arn:aws:iam::063257378709:role/LambdaExecution
            CodeUri: functions/delete-task/
            Handler: main.lambdaHandler
            Layers: 
                - !Ref UtilsLayer
            Events:
                DeleteTaskAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /tasks/{id}
                        Method: delete
    
    UtilsLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Utils
            Description: Layer that includes utils libraries
            ContentUri: lambda-layers/utils
            CompatibleRuntimes: 
                - nodejs12.x
            LicenseInfo: MIT
            RetentionPolicy: Delete

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    GetTasksAPI:
        Description: 'API Gateway endpoint URL for Prod stage for GetTasks function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/'
    GetTasksFunction:
        Description: 'GetTasks Lambda Function ARN'
        Value: !GetAtt GetTasksFunction.Arn
    
    CreateTaskAPI:
        Description: 'API Gateway endpoint URL for Prod stage for CreateTask function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/'
    CreateTaskFunction:
        Description: 'CreateTask Lambda Function ARN'
        Value: !GetAtt CreateTaskFunction.Arn
    
    DetailTaskAPI:
        Description: 'API Gateway endpoint URL for Prod stage for DetailTask function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/'
    DetailTaskFunction:
        Description: 'DetailTask Lambda Function ARN'
        Value: !GetAtt DetailTaskFunction.Arn
    
    DeleteTaskAPI:
        Description: 'API Gateway endpoint URL for Prod stage for DeleteTask function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/'
    DeleteTaskFunction:
        Description: 'DeleteTask Lambda Function ARN'
        Value: !GetAtt DeleteTaskFunction.Arn
    
    
    UtilsLayerARN:
        Value: !Ref UtilsLayer
        Description: UtilsLayer ARN
        Export:
            Name: utils-layer-arn
